"""Add can_create_topics to users

Revision ID: 5f688340f500
Revises: b81ee5a6d904
Create Date: 2026-02-05 13:54:17.398180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f688340f500'
down_revision: Union[str, Sequence[str], None] = 'b81ee5a6d904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('evaluations', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'evaluations', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'projects', ['project_id'], ['project_id'])
    op.create_foreign_key(None, 'evaluations', 'topics', ['topic_id'], ['topic_id'])
    op.add_column('mentoring_logs', sa.Column('mentor_id', sa.UUID(), nullable=False))
    op.add_column('mentoring_logs', sa.Column('session_notes', sa.Text(), nullable=True))
    op.add_column('mentoring_logs', sa.Column('discussion_points', sa.Text(), nullable=True))
    op.add_column('mentoring_logs', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('mentoring_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('mentoring_logs_lecturer_id_fkey', 'mentoring_logs', type_='foreignkey')
    op.create_foreign_key(None, 'mentoring_logs', 'users', ['mentor_id'], ['user_id'])
    op.drop_column('mentoring_logs', 'lecturer_id')
    op.drop_column('mentoring_logs', 'content')
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('related_entity_id', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'action_url')
    op.add_column('projects', sa.Column('claimed_by_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['claimed_by_id'], ['user_id'])
    op.add_column('sprints', sa.Column('name', sa.String(), nullable=True))
    op.add_column('sprints', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('sprints', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'sprints', 'users', ['created_by'], ['user_id'])
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('blocked_reason', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('depends_on', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_team_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['depends_on'], ['task_id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['user_id'])
    op.drop_column('tasks', 'team_id')
    op.drop_column('tasks', 'assignee_id')
    op.add_column('team_members', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('team_members_student_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('team_members', 'student_id')
    op.add_column('teams', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('is_finalized', sa.Boolean(), nullable=False))
    op.alter_column('teams', 'leader_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teams', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['user_id'])
    op.add_column('topics', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('topics', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('topics', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('topics', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('topics', 'dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'topics', 'users', ['approved_by'], ['user_id'])
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['user_id'])
    op.add_column('users', sa.Column('can_create_topics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_topics')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.alter_column('topics', 'dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('topics', 'approved_at')
    op.drop_column('topics', 'approved_by')
    op.drop_column('topics', 'created_by')
    op.drop_column('topics', 'requirements')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.alter_column('teams', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'leader_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('teams', 'is_finalized')
    op.drop_column('teams', 'description')
    op.drop_column('teams', 'created_by')
    op.add_column('team_members', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_student_id_fkey', 'team_members', 'users', ['student_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('team_members', 'user_id')
    op.add_column('tasks', sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_team_id_fkey', 'tasks', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['user_id'])
    op.drop_column('tasks', 'depends_on')
    op.drop_column('tasks', 'blocked_reason')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'assigned_to')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.drop_column('sprints', 'created_at')
    op.drop_column('sprints', 'created_by')
    op.drop_column('sprints', 'name')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'claimed_at')
    op.drop_column('projects', 'claimed_by_id')
    op.add_column('notifications', sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('notifications', 'related_entity_id')
    op.drop_column('notifications', 'notification_type')
    op.add_column('mentoring_logs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentoring_logs', sa.Column('lecturer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mentoring_logs', type_='foreignkey')
    op.create_foreign_key('mentoring_logs_lecturer_id_fkey', 'mentoring_logs', 'users', ['lecturer_id'], ['user_id'])
    op.drop_column('mentoring_logs', 'created_at')
    op.drop_column('mentoring_logs', 'feedback')
    op.drop_column('mentoring_logs', 'discussion_points')
    op.drop_column('mentoring_logs', 'session_notes')
    op.drop_column('mentoring_logs', 'mentor_id')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.alter_column('evaluations', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('evaluations', 'updated_at')
    op.drop_column('evaluations', 'score')
    op.drop_column('evaluations', 'project_id')
    op.drop_column('evaluations', 'topic_id')
    op.drop_column('evaluations', 'team_id')
    # ### end Alembic commands ###
